course_abrv_to_department = {
    "ANTH": "Anthropology",
    "ART CS": "Art (Creative Studies)",
    "ARTHI": "Art History",
    "ARTST": "Art Studio",
    "AS AM": "Asian American Studies",
    "ASTRO": "Astronomy",
    "BIOL CS": "Biology (Creative Studies)",
    "BMSE": "Biomolecular Science and Engineering",
    "BL ST": "Black Studies",
    "CH E": "Chemical Engineering",
    "CHEM": "Chemistry and Biochemistry",
    "CHEM CS": "Chemistry and Biochemistry (Creative Studies)",
    "CH ST": "Chicano Studies",
    "CHIN": "Chinese",
    "CLASS": "Classics",
    "COMM": "Communication",
    "C LIT": "Comparative Literature",
    "CMPSC": "Computer Science",
    "CMPSCCS": "Computer Science (Creative Studies)",
    "CNCSP": "Counseling, Clinical, School Psychology",
    "DANCE": "Dance",
    "EARTH": "Earth Science",
    "EACS": "East Asian Cultural Studies",
    "EEMB": "Ecology, Evolution & Marine Biology",
    "ECON": "Economics",
    "ED": "Education",
    "ED S": "Education",
    "ED E": "Education",
    "ED M": "Education",
    "ED WL": "Education",
    "ECE": "Electrical Computer Engineering",
    "ENGR": "Engineering Sciences",
    "ENGL": "English",
    "ESM": "Environmental Science & Management",
    "ENV S": "Environmental Studies",
    "ESS": "Exercise & Sport Studies",
    "ES": "Exercise Sport",
    "ES 1-": "Exercise Sport",
    "FEMST": "Feminist Studies",
    "FLMST": "Film Studies",
    "FR": "French",
    "GEN S CS": "General Studies (Creative Studies)",
    "GEOG": "Geography",
    "GER": "German",
    "GPS": "Global Peace and Security",
    "GLOBL": "Global Studies",
    "GREEK": "Greek",
    "HEB": "Hebrew",
    "HIST": "History",
    "INT": "Interdisciplinary",
    "INT CS": "Interdisciplinary (Creative Studies)",
    "ITAL": "Italian",
    "JAPAN": "Japanese",
    "KOR": "Korean",
    "LATIN": "Latin",
    "LAIS": "Latin American and Iberian Studies",
    "LING": "Linguistics",
    "LIT CS": "Literature (Creative Studies)",
    "MARSC": "Marine Science",
    "MATRL": "Materials",
    "MATH": "Mathematics",
    "MATH CS": "Mathematics (Creative Studies)",
    "ME": "Mechanical Engineering",
    "MAT": "Media Arts and Technology",
    "ME ST": "Medieval Studies",
    "MES": "Middle East Studies",
    "MS": "Military Science",
    "MCDB": "Molecular, Cellular & Develop. Biology",
    "MUS": "Music",
    "MUS CS": "Music (Creative Studies)",
    "MUS A": "Music Performance Laboratories",
    "PHIL": "Philosophy",
    "PHYS": "Physics",
    "PHYS CS": "Physics",
    "POL S": "Political Science",
    "PORT": "Portuguese",
    "PSY": "Psychology",
    "RG ST": "Religious Studies",
    "RENST": "Renaissance Studies",
    "SLAV": "Slavic",
    "SOC": "Sociology",
    "SPAN": "Spanish",
    "SHS": "Speech & Hearing Sciences",
    "PSTAT": "Statistics & Applied Probability",
    "TMP": "Technology Management",
    "THTR": "Theater",
    "WRIT": "Writing",
}
